services:
  pg-database:
    # our postgres container
    image: postgres:latest 
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - ./ny_taxi_postgres_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
  pg-admin:
  # our pgadmin container, persist configuration data by mounting on pgadmin folder
    image: dpage/pgadmin4:latest
    environment: 
    - PGADMIN_DEFAULT_EMAIL=admin@admin.com
    - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    ports:
      - "8080:80"
  pipeline:
    image: ingest_data:v001
    environment:
      - username=root
      - password=root
      - host=pg-database
      - port=5432
      - database=ny_taxi
      - tablename=zones
      - url="https://d37ci6vzurychx.cloudfront.net/misc/taxi+_zone_lookup.csv"
    depends_on:
      - pg-database
   
  


